export const pubs = [
 {
   "id": 0,
   "title": "Creation of a Really Big Gun for Revenge upon the Bastard Who Killed My Father",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Book Chapter",
   "link": "http://google.com",
   "date": 1994,
   "image": "img1"
 },
 {
   "id": 1,
   "title": "Formation of a Really Big Gun for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Basic",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 1995,
   "image": "img2"
 },
 {
   "id": 2,
   "title": "Formation of a Preternaturally Cute Doggo for The Hell of It",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Bamford",
   "moreAuthors": true,
   "category": "Clinical",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 1996,
   "image": "img3"
 },
 {
   "id": 3,
   "title": "Creation of a Preternaturally Cute Doggo for World Domination",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Abstract",
   "link": "http://google.com",
   "date": 1997,
   "image": "img4"
 },
 {
   "id": 4,
   "title": "Creation of a Bouncy House for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Basic",
   "type": "Editorial",
   "link": "http://google.com",
   "date": 1998,
   "image": "img5"
 },
 {
   "id": 5,
   "title": "Formation of a Superweapon for The Hell of It",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": false,
   "category": "Clinical",
   "type": "Book Chapter",
   "link": "http://google.com",
   "date": 1999,
   "image": "img6"
 },
 {
   "id": 6,
   "title": "Creation of a Really Big Gun for Revenge upon the Bastard Who Killed My Father",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 2000,
   "image": "img7"
 },
 {
   "id": 7,
   "title": "Formation of a Bouncy House for World Domination",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Livi",
   "moreAuthors": true,
   "category": "Basic",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 2001,
   "image": "img8"
 },
 {
   "id": 8,
   "title": "Development of a Really Big Gun for World Domination",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Clinical",
   "type": "Abstract",
   "link": "http://google.com",
   "date": 2002,
   "image": "img9"
 },
 {
   "id": 9,
   "title": "Development of a Totally Inconspicuous Box for World Domination",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Editorial",
   "link": "http://google.com",
   "date": 2003,
   "image": "img10"
 },
 {
   "id": 10,
   "title": "Creation of a Preternaturally Cute Doggo for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Basic",
   "type": "Book Chapter",
   "link": "http://google.com",
   "date": 2004,
   "image": "img11"
 },
 {
   "id": 11,
   "title": "Development of a Superweapon for Revenge upon the Bastard Who Killed My Father",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": false,
   "category": "Clinical",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 2005,
   "image": "img12"
 },
 {
   "id": 12,
   "title": "Formation of a Really Big Gun for Revenge upon the Bastard Who Killed My Father",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Fuller",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 2006,
   "image": "img13"
 },
 {
   "id": 13,
   "title": "Formation of a Preternaturally Cute Doggo for The Hell of It",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Basic",
   "type": "Abstract",
   "link": "http://google.com",
   "date": 2007,
   "image": "img14"
 },
 {
   "id": 14,
   "title": "Creation of a Totally Inconspicuous Box for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Clinical",
   "type": "Editorial",
   "link": "http://google.com",
   "date": 2008,
   "image": "img15"
 },
 {
   "id": 15,
   "title": "Development of a Bouncy House for The Hell of It",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Book Chapter",
   "link": "http://google.com",
   "date": 2009,
   "image": "img16"
 },
 {
   "id": 16,
   "title": "Creation of a Giant Raging Dinosaur for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": false,
   "category": "Basic",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 2010,
   "image": "img17"
 },
 {
   "id": 17,
   "title": "Formation of a Superweapon for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Clinical",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 2011,
   "image": "img18"
 },
 {
   "id": 18,
   "title": "Formation of a Giant Raging Dinosaur for The Hell of It",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Robinson",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Abstract",
   "link": "http://google.com",
   "date": 2012,
   "image": "img19"
 },
 {
   "id": 19,
   "title": "Creation of a Bouncy House for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Basic",
   "type": "Editorial",
   "link": "http://google.com",
   "date": 2013,
   "image": "img20"
 },
 {
   "id": 20,
   "title": "Formation of a Giant Raging Dinosaur for The Hell of It",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": false,
   "category": "Clinical",
   "type": "Book Chapter",
   "link": "http://google.com",
   "date": 2014,
   "image": "img21"
 },
 {
   "id": 21,
   "title": "Formation of a Superweapon for The Hell of It",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 2015,
   "image": "img22"
 },
 {
   "id": 22,
   "title": "Formation of a Giant Raging Dinosaur for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Basic",
   "type": "Original Research",
   "link": "http://google.com",
   "date": 2016,
   "image": "img23"
 },
 {
   "id": 23,
   "title": "Development of a Totally Inconspicuous Box for The Hell of It",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Clinical",
   "type": "Abstract",
   "link": "http://google.com",
   "date": 2017,
   "image": "img24"
 },
 {
   "id": 24,
   "title": "Creation of a Giant Raging Dinosaur for teh lulz",
   "publication": "Trying Times",
   "author1": "Smith",
   "author2": "Burns",
   "author3": "Simpson",
   "moreAuthors": true,
   "category": "Engineering",
   "type": "Editorial",
   "link": "http://google.com",
   "date": 2017,
   "image": "img25"
 }
]
